// <auto-generated />
using ApiProduto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProduto.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiProduto.Domain.Entidades.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descriscao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descriscao");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_marcas");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("ApiProduto.Domain.Entidades.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descriscao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descriscao");

                    b.Property<int>("Estoque")
                        .HasColumnType("int")
                        .HasColumnName("estoque");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco_venda");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("id")
                        .HasName("pk_produto");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_produto_marca_id");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("ApiProduto.Domain.Entidades.Produto", b =>
                {
                    b.HasOne("ApiProduto.Domain.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produto_marcas_marca_id");

                    b.Navigation("Marca");
                });
#pragma warning restore 612, 618
        }
    }
}
